ci: ajuste

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,11 +27,19 @@ jobs:
 
     - name: Verify Code Coverage
       run: |
-        COVERAGE=$(grep -oP '(?<=<td class="ctr2">)[0-9]+(?=%</td>)' target/site/jacoco/index.html | tr -d '\n')      
-        if [ "$COVERAGE" -ge "10" ]; then
+        COVERAGE=$(grep -oP '(?<=<td class="ctr2">)[0-9]+(?=%\?)' target/site/jacoco/index.html)
+        COVERAGE_DEC=$(echo "scale=2; $COVERAGE/100" | bc)
+        if (( $(echo "$COVERAGE_DEC > 0.1" | bc -l) )); then
           echo "Code coverage is $COVERAGE%. Test passed!"
         else
           echo "Code coverage is $COVERAGE%. Test failed! Required 10%."
         exit 1
         fi
+        #COVERAGE=$(grep -oP '(?<=<td class="ctr2">)[0-9]+(?=%\?)' target/site/jacoco/index.html)      
+        #if [ "$COVERAGE" -ge "10" ]; then
+        #  echo "Code coverage is $COVERAGE%. Test passed!"
+        #else
+        #  echo "Code coverage is $COVERAGE%. Test failed! Required 10%."
+        #exit 1
+        #fi
         
